# Generated by Django 2.2 on 2020-06-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'managed': False},
        ),
    ]
