# Generated by Django 2.2 on 2020-06-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(blank=True, db_column='BILLNO', max_length=255, null=True)),
                ('billdate1', models.CharField(blank=True, db_column='BILLDATE1', max_length=255, null=True)),
                ('billdate', models.CharField(blank=True, db_column='BILLDATE', max_length=255, null=True)),
                ('yearmonth', models.CharField(blank=True, db_column='YEARMONTH', max_length=255, null=True)),
                ('days', models.CharField(blank=True, db_column='DAYS', max_length=255, null=True)),
                ('parentname', models.CharField(blank=True, db_column='PARENTNAME', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, null=True)),
                ('shopcode', models.CharField(blank=True, db_column='SHOPCODE', max_length=255, null=True)),
                ('shopname', models.CharField(blank=True, db_column='SHOPNAME', max_length=255, null=True)),
                ('shopproperty', models.CharField(blank=True, db_column='SHOPPROPERTY', max_length=255, null=True)),
                ('whareatypecode', models.CharField(blank=True, db_column='WHAREATYPECODE', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=255, null=True)),
                ('goodsid', models.CharField(blank=True, db_column='GOODSID', max_length=255, null=True)),
                ('goodscode', models.CharField(blank=True, db_column='GOODSCODE', max_length=255, null=True)),
                ('goodsname', models.CharField(blank=True, db_column='GOODSNAME', max_length=255, null=True)),
                ('singleproductid', models.CharField(blank=True, db_column='SINGLEPRODUCTID', max_length=255, null=True)),
                ('singleproductcode', models.CharField(blank=True, db_column='SINGLEPRODUCTCODE', max_length=255, null=True)),
                ('singleproductname', models.CharField(blank=True, db_column='SINGLEPRODUCTNAME', max_length=255, null=True)),
                ('weight', models.CharField(blank=True, db_column='WEIGHT', max_length=255, null=True)),
                ('laborcoststandard', models.CharField(blank=True, db_column='LABORCOSTSTANDARD', max_length=255, null=True)),
                ('laborcostactual', models.CharField(blank=True, db_column='LABORCOSTACTUAL', max_length=255, null=True)),
                ('discount', models.CharField(blank=True, db_column='DISCOUNT', max_length=255, null=True)),
                ('qty', models.CharField(blank=True, db_column='QTY', max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=38, null=True)),
                ('amountretail', models.CharField(blank=True, db_column='AMOUNTRETAIL', max_length=255, null=True)),
                ('amounttag', models.CharField(blank=True, db_column='AMOUNTTAG', max_length=255, null=True)),
                ('actualcost', models.CharField(blank=True, db_column='ACTUALCOST', max_length=255, null=True)),
                ('amountsettle', models.CharField(blank=True, db_column='AMOUNTSETTLE', max_length=255, null=True)),
                ('amountverify', models.CharField(blank=True, db_column='AMOUNTVERIFY', max_length=255, null=True)),
                ('amountsharesettle', models.CharField(blank=True, db_column='AMOUNTSHARESETTLE', max_length=255, null=True)),
                ('amountshare', models.CharField(blank=True, db_column='AMOUNTSHARE', max_length=255, null=True)),
                ('couponsno', models.CharField(blank=True, db_column='COUPONSNO', max_length=255, null=True)),
                ('issettlement', models.CharField(blank=True, db_column='ISSETTLEMENT', max_length=255, null=True)),
                ('discountrate', models.CharField(blank=True, db_column='DISCOUNTRATE', max_length=255, null=True)),
                ('discounttype', models.CharField(blank=True, db_column='DISCOUNTTYPE', max_length=255, null=True)),
                ('sourcebillno', models.CharField(blank=True, db_column='SOURCEBILLNO', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=255, null=True)),
                ('vipcardno', models.CharField(blank=True, db_column='VIPCARDNO', max_length=255, null=True)),
                ('orderbilltype', models.CharField(blank=True, db_column='ORDERBILLTYPE', max_length=255, null=True)),
                ('generaltype', models.CharField(blank=True, db_column='GENERALTYPE', max_length=255, null=True)),
                ('ddremark', models.CharField(blank=True, db_column='DDREMARK', max_length=255, null=True)),
                ('orderamount', models.CharField(blank=True, db_column='ORDERAMOUNT', max_length=255, null=True)),
                ('orderqty', models.CharField(blank=True, db_column='ORDERQTY', max_length=255, null=True)),
                ('timestamp', models.CharField(blank=True, db_column='TIMESTAMP', max_length=255, null=True)),
                ('brand', models.CharField(blank=True, db_column='BRAND', max_length=255, null=True)),
                ('holiday', models.CharField(blank=True, db_column='HOLIDAY', max_length=255, null=True)),
                ('classi', models.CharField(blank=True, db_column='CLASSI', max_length=255, null=True)),
                ('classii', models.CharField(blank=True, db_column='CLASSII', max_length=255, null=True)),
                ('productname', models.CharField(blank=True, db_column='PRODUCTNAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Business_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='testSalesVolumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdate', models.DateField(blank=True, db_column='BILLDATE1', max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'testSalesVolumn',
                'managed': False,
            },
        ),
    ]
